services:
  devboard-auth:
    build:
      context: .
    container_name: devboard-auth
    restart: unless-stopped
    env_file: .env
    ports:
      - "8001:8000"
    networks:
      - devboard-network

networks:
  devboard-network:
    name: devboard-network
    external: true
